FROM python:3.9-slim

WORKDIR /app
RUN pip install fastapi uvicorn pydantic elasticsearch==8.11.0
COPY injest.py .
COPY key.pem .
COPY cert.pem .
CMD ["uvicorn", "injest:app", "--host", "0.0.0.0", "--port", "443", "--ssl-keyfile", "key.pem", "--ssl-certfile", "cert.pem"]
